### ISSUE TITLE
zef install test failed

### ISSUE THREAD

**Issue by xerox51** [frithnanth/raku-Spreadsheet-Libxlsxio#1]
[Spreadsheet::Libxlsxio] Cannot unbox a type object (Str) to a str.
[Spreadsheet::Libxlsxio]   in sub xlsxioread_sheet_open at /Users/johnweng/.zef/store/Spreadsheet-Libxlsxio-0.0.1.tar.gz/Spreadsheet-Libxlsxio-0.0.1/lib/.precomp/14C96CC786A21EF96947FD43C66C259A5ED93A2C/33/336B97E6BE6404D6345A0287032D6EF08C5520D5 line 1
[Spreadsheet::Libxlsxio]   in block <unit> at t/01-raw-read.rakutest line 45
[Spreadsheet::Libxlsxio]     # Failed test 'library version'
[Spreadsheet::Libxlsxio]     # at t/02-raw-write.rakutest line 13
[Spreadsheet::Libxlsxio]     # expected: $(0, 2, 29)
[Spreadsheet::Libxlsxio]     #      got: $(0, 2, 30)
[Spreadsheet::Libxlsxio]     # Failed test 'library version as string'
[Spreadsheet::Libxlsxio]     # at t/02-raw-write.rakutest line 14
[Spreadsheet::Libxlsxio]     # expected: '0.2.29'
[Spreadsheet::Libxlsxio]     #      got: '0.2.30'
[Spreadsheet::Libxlsxio]     # You failed 2 tests of 2
[Spreadsheet::Libxlsxio] # Failed test 'version'
[Spreadsheet::Libxlsxio] # at t/02-raw-write.rakutest line 10
[Spreadsheet::Libxlsxio]     # Failed test 'spreadsheet content'
[Spreadsheet::Libxlsxio]     # at t/02-raw-write.rakutest line 47
[Spreadsheet::Libxlsxio]     # expected: $["[Sheet1]", "Col1", "Col2", "Test", "0", "Test", "1", "Test", "2", "Test", "3", "Test", "4", "Test", "5", "Test", "6", "Test", "7", "Test", "8", "Test", "9"]
[Spreadsheet::Libxlsxio]     #      got: $["[Sheet1]", "Col1", "Col2"]
[Spreadsheet::Libxlsxio]     # You failed 1 test of 3
[Spreadsheet::Libxlsxio] # Failed test 'write'
[Spreadsheet::Libxlsxio] # at t/02-raw-write.rakutest line 17
[Spreadsheet::Libxlsxio] # You failed 2 tests of 2
[Spreadsheet::Libxlsxio]     # Failed test 'spreadsheet content'
[Spreadsheet::Libxlsxio]     # at t/03-oo.rakutest line 83
[Spreadsheet::Libxlsxio]     # expected: $["[Sheet1]", "a", "b", "c", "1", "2", "3", "1.1", "2.2", "3.3", "44300", "44301", "44302", "2.1", "4.2", "6.3"]
[Spreadsheet::Libxlsxio]     #      got: $["[Sheet1]", "a", "b", "c"]
[Spreadsheet::Libxlsxio]     # You failed 1 test of 1
[Spreadsheet::Libxlsxio] # Failed test 'read & process the whole spreadsheet'
[Spreadsheet::Libxlsxio] # at t/03-oo.rakutest line 74
[Spreadsheet::Libxlsxio]     # Failed test 'verify spreadsheet content'
[Spreadsheet::Libxlsxio]     # at t/03-oo.rakutest line 108
[Spreadsheet::Libxlsxio]     # expected: $["[Sheet1]", "Col1", "Col2", "Col3", "Col4", "Test0", "0", "3.1415926535897931159979634685442", "44402.00000577547", "Test1", "1", "3.1415926535897931159979634685442", "44402.00000577547", "Test2", "2", "3.1415926535897931159979634685442", "44402.00000577547", "Test3", "3", "3.1415926535897931159979634685442", "44402.00000577547", "Test4", "4", "3.1415926535897931159979634685442", "44402.00000577547", "Test5", "5", "3.1415926535897931159979634685442", "44402.00000577547", "Test6", "6", "3.1415926535897931159979634685442", "44402.00000577547", "Test7", "7", "3.1415926535897931159979634685442", "44402.00000577547", "Test8", "8", "3.1415926535897931159979634685442", "44402.00000577547", "Test9", "9", "3.1415926535897931159979634685442", "44402.00000577547"]
[Spreadsheet::Libxlsxio]     #      got: $["[Sheet1]", "Col1", "Col2", "Col3", "Col4"]
[Spreadsheet::Libxlsxio] Use of uninitialized value @values[8] of type Any in string context.
[Spreadsheet::Libxlsxio] Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
[Spreadsheet::Libxlsxio]   in sub to-date at /Users/johnweng/.zef/store/Spreadsheet-Libxlsxio-0.0.1.tar.gz/Spreadsheet-Libxlsxio-0.0.1/lib/Spreadsheet/Libxlsxio.rakumod (Spreadsheet::Libxlsxio) line 98
[Spreadsheet::Libxlsxio]     # Failed test 'date conversion'
[Spreadsheet::Libxlsxio]     # at t/03-oo.rakutest line 109
[Spreadsheet::Libxlsxio]     # expected: '2021-07-25T00:00:00Z'
[Spreadsheet::Libxlsxio]     #      got: '1899-12-30T00:00:00Z'
[Spreadsheet::Libxlsxio]     # You failed 2 tests of 6
[Spreadsheet::Libxlsxio] # Failed test 'write'
[Spreadsheet::Libxlsxio] # at t/03-oo.rakutest line 86
[Spreadsheet::Libxlsxio] # You failed 2 tests of 6
===> Testing [FAIL]: Spreadsheet::Libxlsxio:ver<0.0.1>:auth<cpan:FRITH>
Aborting due to test failure: Spreadsheet::Libxlsxio:ver<0.0.1>:auth<cpan:FRITH> (use --force-test to override)

**Comment by xerox51** [comment]
I use --force-test instruction to install this module at last.
It works normally.
Thanks!

**Comment by frithnanth** [comment]
Hi,
thanks for opening this issue: the test on the C library version should not have been public; I released a new version to correct that.

Funny thing: the C library GitHub page listed a v. 0.2.29 release, but no 0.2.30. When one downloads the source via the release link gets the former version, while the latter pops out if one clones the repository. In any case now I test for both version numbers.

If you want to see the test result for the version number run the tests setting the `TEST_AUTHOR` environment variable, like this:

`TEST_AUTHOR=1 t/01-raw-read.rakutest`
`TEST_AUTHOR=1 t/02-raw-write.rakutest`

About the other errors you reported, I was not able to replicate them. Out of curiosity, what operating system were you using? The curiosity spring from what you said about the module working normally, which should not be so, since the tests report those errors.
Anyway reopen the issue if you have other information about it.

**Comment by xerox51** [comment]
My operating system is bigsur 11.0 on Mac.
After I used --force-test instruction to install the module.
Follow your usage example,I used the module to write some string type data to excel without any exception occured.
And I did not write any other type data to excel.
Until now, I did not meet any other problem.
